from pydantic import BaseModel, HttpUrl, Field
from typing import List, Optional, Dict, Any
from datetime import datetime


class Paper(BaseModel):
    """Metadata for an arXiv paper."""
    arxiv_id: str
    title: str
    abstract: str
    authors: List[str]
    primary_category: str
    categories: List[str]
    published: datetime
    updated: datetime
    pdf_url: Optional[HttpUrl] = None
    local_pdf_path: Optional[str] = None
    local_text_path: Optional[str] = None
    indexed: bool = False


class ChunkRecord(BaseModel):
    """A single text chunk from a paper."""
    paper_id: str
    chunk_id: int
    text: str
    source: str
    embedding: Optional[List[float]] = None


class SearchResult(BaseModel):
    """A single result from a semantic search."""
    paper_id: str
    chunk_id: int
    text: str
    score: float           # lower = more similar for L2; higher for cosine
    title: Optional[str] = None
    authors: Optional[List[str]] = None
    published: Optional[str] = None
    abstract: Optional[str] = None


class ResearchPlan(BaseModel):
    """A structured research plan generated by the planning chain."""
    question: str
    concepts: List[str] = Field(default_factory=list)
    queries: List[str] = Field(default_factory=list)
    categories: List[str] = Field(default_factory=list)
    paper_types: List[str] = Field(default_factory=list)
    raw: str = ""


class ResearchReport(BaseModel):
    """Full output from the research agent."""
    question: str
    plan: Optional[ResearchPlan] = None
    synthesis: str = ""
    critique: str = ""
    sources: List[SearchResult] = Field(default_factory=list)
    faithfulness_score: float = 0.0
    coverage_score: float = 0.0
    metadata: Dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=datetime.utcnow)
